[package]
name = "entrypoint"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
front = { path = "../front" }
back_wasm = { path = "../back_wasm" }
wasmtime = "7.0.0"