[package]
name = "cc"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
front = { path = "../front" }
middle = { path = "../middle" }
stack_vm = { path = "../stack_vm" }
anyhow = "1.0.70"